### ISSUE TITLE
Does this work for captive portals?

### ISSUE THREAD

**Issue by lyricalpolymath** [jzplusplus/GlassWifiConnect#11]
I haven't been able to test it yet, but does this allow you to connect in those situations where the connection redirects you to a captive portal, a webpage where you have to insert username and/or just the password?

I know of a method to connect to captive portals with only a confirm/connect button, but not one where you have to input the values in the textfield
any luck?
thanks in advance

**Comment by samheather** [comment]
No it doesn't. 

Sam

**Comment by jzplusplus** [comment]
This project is to allow you to connect to WPA Enterprise networks, which require a username and password. They usually do not have a captive portal, since your credentials are already given.
