### ISSUE TITLE
Semicolons in the Fields Cause Authentication Issues

### ISSUE THREAD

**Issue by Zeklandia** [jzplusplus/GlassWifiConnect#3]
I have a semicolon in one of the fields and it causes the authentication to fail because the app reads it as the end of a field.

**Comment by Zeklandia** [comment]
Has this been fixed?

**Comment by jzplusplus** [comment]
Yes. The latest commit fixes it. (There is still an issue if any of the fields include a semicolon followed by the name of one of the fields followed by a colon, but that should be much less likely than just a semicolon)
