### ISSUE TITLE
XE16 Compatibility

### ISSUE THREAD

**Issue by tehDrew** [jzplusplus/GlassWifiConnect#9]
Some code could use updating for XE16.11

**Comment by cj2001** [comment]
Any word on getting things running for XE16?  Some of us rely on this for Glass connectivity.

**Comment by jzplusplus** [comment]
As soon as I graduate from college I'll get back to working on this.

**Comment by samheather** [comment]
I had a go at fixing this, but I'm really not familiar with WifiConfiguration in KitKat.  I've requested the Glass team as well that they add this feature to Glass - I think it should have been an early feature.
